/*
    DO NOT MODIFY THIS FILE DIRECTLY!

    It is autogenerated from libs/Drawing/metadata.json.
    Update that file and then run scripts/generate_stubs.py to re-generate
    this file.
*/
namespace MPlex.Native.Drawing
{
    internal class DrawingNativeBridge : Common.NativeBridge
    {
        public override int Send(string cmd, params object[] args)
        {
            switch (cmd)
            {
                case "create-bitmap-file": return Methods.CreateBitmapFile((System.Collections.Generic.Dictionary<int, object>)args[0], (string)args[1]);
                case "create-bitmap-size": return Methods.CreateBitmapSize((System.Collections.Generic.Dictionary<int, object>)args[0], (int)args[1], (int)args[2]);
                case "save-bitmap": return Methods.SaveBitmap((System.Collections.Generic.Dictionary<int, object>)args[0], (string)args[1]);
            }
            return SetError(-1, "Unknown command.");
        }
    }
}
