# DO NOT MODIFY THIS FILE DIRECTLY!
#
# It is autogenerated from libs/Drawing/metadata.json.
# Update that file and then run scripts/generate_stubs.py to re-generate
# this file.

import mplex.native as _native

from .methods import *

_commands = {
	"create-bitmap-file": create_bitmap_file,
	"create-bitmap-size": create_bitmap_size,
	"save-bitmap": save_bitmap,
}

_native.REGISTRY.register('Drawing', _native.NativeBridge(_commands))
